- src/components/layout/Registry.tsx
- src/components/ui/agents/AgentStarterCard.tsx
fix link of starter card and mobile registry banner scale
> Registry Ui fixes

- src/components/layout/Hero.tsx
- src/components/ui/agents/AgentSelector.tsx
adds selcted agent to session storage
> Persist Selected Agent 

- src/components/layout/Hero.tsx
- src/components/ui/agents/AgentSelector.tsx
> Fix margin agents

- src/components/layout/ManageAccountsDialog.tsx
> add disconnect btn and remove reown noise connected evm account

- src/components/layout/AgentDetail.tsx
- src/components/layout/AiChat.tsx
- src/components/layout/Hero.tsx
> Add chat into registry detail page

- src/lib/data/navData.ts
- src/lib/url.ts
> Add api key links to nav and footer

- src/components/layout/Hero.tsx
- src/lib/url.ts
> embed agent button on hero

- src/components/layout/AgentSection.tsx
- src/components/layout/ChatContent.tsx
- src/components/layout/DetailsSidebar.tsx
- src/components/ui/agents/AgentSelector.tsx
1. Link to Chat component on Agent Section
2. Link To Chat component instead of wallet
3. Add logic for using selected agent by query params 
4. add scroll to selected agent in agent selector component 
5. add optional url param prompt to chat component
6. improve linking speed by using .prefetch & .replace
> Agent id Param & links

- src/components/layout/DetailsSidebar.tsx
- src/components/ui/agents/AgentCard.tsx
> Embed button

- src/lib/agentConstants.ts
- Updated the  constant to reflect the new agent ID.
> Update: Change BITTE_AGENTID 

- src/components/layout/ChatContent.tsx
- src/components/layout/DetailsSidebar.tsx
- src/components/ui/agents/AgentCard.tsx
- src/components/ui/agents/AgentSelector.tsx
- Updated agent selection in ChatContent to consider drawer state - mobile
- Add padding to mobile as well
> fix: Improve mobile agent selection logic in debug and default modes

- src/components/layout/AgentSection.tsx
- Updated CSS classes in AgentSection to restrict vertical overflow while maintaining horizontal scrolling functionality.
> fix: Prevent vertical overflow in AgentSection component (#173)

- src/components/layout/AgentImage.tsx
- src/components/layout/AgentRow.tsx
- src/components/layout/AgentSection.tsx
- src/components/layout/DetailsSidebar.tsx
- src/components/ui/agents/AgentCard.tsx
- src/lib/utils/agent.ts
- Created AgentImage component to handle fallback image loading
- Extracted image and URL generation logic into agent utility functions
- Updated AgentCard and DetailsSidebar to use new AgentImage and utility functions
> feat: Add AgentImage component and agent URL utility functions

- src/components/ui/agents/AgentSelector.tsx
- src/components/ui/agents/AllAgents.tsx
- src/hooks/useAssistants.ts
- Updated search logic in AllAgents component to include agent ID in search criteria.
- Increased the fetch limit for agents from 100 to 150 in useAssistants hooks to improve data retrieval.
> fix: Enhance agent search functionality and increase fetch limit for agents

- src/components/layout/Related.tsx
- Changed layout from flexbox to grid for better responsiveness.
- Adjusted column configuration for different screen sizes.
> fix: update layout of RelatedTemplates component to use grid system to fix width

- src/components/ui/agents/AllAgents.tsx
- src/components/ui/agents/Filters.tsx
- Added background color to the sticky div in AllAgents for improved visibility.
- Removed max height restriction from AccordionContent in Filters for better content display.
> refactor: adjust filters height and overflow

- src/components/ui/agents/Filters.tsx
- Updated AccordionContent in Filters to allow vertical scrolling with a maximum height for better usability on larger datasets.
> refactor: enhance Filters component with scrollable content area

- src/app/(dashboard)/build-agents/config/page.tsx
- src/app/(dashboard)/build-agents/page.tsx
> Add disabled logic in next/create buttons

- next.config.js
- package.json
- pnpm-lock.yaml
- src/app/(dashboard)/chat/[id]/page.tsx
- src/app/(dashboard)/chat/page.tsx
- src/components/layout/AiChat.tsx
- src/components/layout/ChatContent.tsx
- src/components/nav-main.tsx
- src/components/root-sidebar.tsx
there was 4 console errors on chat:
- breadcrumb li inside another li
- wallet not selected
- lottie undefined
- link href hydratation failed
all then fixed now
> fix console errors on /chat

- next.config.js
update Content-Security-Policy to include media sources from Google Cloud
> fix: video player not loading any videos

- src/components/layout/Home.tsx
- src/components/layout/MpcSection.tsx
- src/components/layout/TextSection.tsx
- src/lib/url.ts
- tailwind.config.ts
- Introduced a new MpcSection component for displaying MPC-related information and functionality.
- Updated Home component to include the new MpcSection.
- Added a new Tailwind color 'mb-purple-10' for styling purposes.
- Updated URL configuration to include MPC_URL for easy access.
> Add MPC section to Home layout and update Tailwind config

- src/components/layout/Home.tsx
- src/components/layout/MCPSection.tsx
- src/lib/url.ts
- Renamed MpcSection to MCPSection for consistency.
- Added new MCPSection component to the layout, featuring a copy-to-clipboard functionality for the MCP URL.
- Updated URL configuration to change MPC_URL to MCP_URL for clarity.
> fix: MCP typos in components

- src/components/AgentSectionComp.tsx
- src/components/layout/HeroComponent.tsx
- Reorganized imports for clarity and consistency.
- Modified button structure to enhance accessibility and maintainability.
- Updated link destinations for the 'Browse Agents' and 'Build Chain Agent' buttons.
> refactor: change Build Chain Agent redirect

- package.json
- pnpm-lock.yaml
- src/app/layout.tsx
- src/components/layout/AiChat.tsx
- src/components/layout/NewHero.tsx
bumps chat and react packages versions
> bump versions

- src/components/agent-builder/ImageUploader.tsx
> change remove image icon

- package.json
- pnpm-lock.yaml
There are some critical dependabot warnings and this should apparently resolve them (at least the net ones which seem like plenty).
https://github.com/BitteProtocol/website/security/dependabot
> Security: Update Next (minor bump)

- src/lib/agentConstants.ts
> Update action text for bitte-sui-agent to reflect correct WAL swap

- src/app/api/generate-image/route.ts
- src/lib/data/partnerData.ts
- src/lib/url.ts
There was a bunch of commented/dead code that is now removed (closes #277).
> Remove Dead Arweave Code

- .github/workflows/pull-request.yaml
- package.json
- pnpm-lock.yaml
Note that build is excluded here, because its performed by the Vercel deployment. Closes #271
> Add CI File for Lint & Test

- src/components/layout/AiChat.tsx
Merging this adds MCP tool to all agents - currently using `https://mcp.bitte.ai/sse`.
MCP server can also be overridden via prompt i.e.
> Set MCPServerUrl (enables mcp tool)

- package.json
- pnpm-lock.yaml
- src/components/layout/AiChat.tsx
- src/components/layout/WelcomeMessage.tsx
- src/config/chat-options.tsx
this : 
- adds TokenList component on website
- take out <BitteAiChat> config for a separate file, as it is becoming large, and hard to maintain
- fixes all types, and improve typing ( remove all anys )
> add token-list-component

- src/app/styles/globals.css
- src/components/ui/agents/AgentSelector.tsx
- src/components/ui/agents/Filters.tsx
this fixes the scrollbar colors
still missing on the chat itself, theres a release to come with the fix on the chat too.
this should fix scrollbars of agents selections, and network filters.
> fix scrollbars on website
